CREATE TABLE IF NOT EXISTS inv_dts (
  id BIGSERIAL PRIMARY KEY,
  inventory_id BIGINT REFERENCES inventories(id) ON DELETE RESTRICT,
  item_unit_id BIGINT REFERENCES item_units(id) ON DELETE RESTRICT,
  vat_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  pph23_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  ref_id BIGINT,
  item_id BIGINT,
  product_uuid TEXT,
  ref_type TEXT,
  item_type TEXT,
  gen_code TEXT,
  remark TEXT,
  vat_perc DECIMAL(20, 5),
  vat_perc_am DECIMAL(20, 5),
  pph23_perc DECIMAL(20, 5),
  pph23_perc_am DECIMAL(20, 5),
  is_vat INT,
  is_pph23 INT,
  qty_invoice DECIMAL(20, 5),
  qty_out DECIMAL(20, 5),
  qty DECIMAL(20, 5),
  price_sell DECIMAL(20, 5),
  price_buy DECIMAL(20, 5),
  subtotal_sell DECIMAL(20, 5),
  subtotal_buy DECIMAL(20, 5),
  total_am DECIMAL(20, 5),
  expired_at date,
  item_json JSONB,
  created_by_id BIGINT,
  updated_by_id BIGINT,
  deleted_by_id BIGINT,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone
);