CREATE TABLE IF NOT EXISTS stock_closings (
  id SERIAL PRIMARY KEY,
  warehouse_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  item_id BIGINT REFERENCES products(id) ON DELETE RESTRICT,
  closing_at DATE NOT NULL,
  last_closing_at DATE NOT NULL,
  begin_qty DECIMAL(20, 5) NOT NULL,
  in_qty DECIMAL(20, 5) NOT NULL,
  out_qty DECIMAL(20, 5) NOT NULL,
  adjustment_qty DECIMAL(20, 5) NOT NULL,
  end_qty DECIMAL(20, 5) NOT NULL,
  price_sell DECIMAL(20, 5) NOT NULL,
  price_buy DECIMAL(20, 5) NOT NULL,
  total_value_sell DECIMAL(20, 5) NOT NULL,
  total_value_buy DECIMAL(20, 5) NOT NULL,
  is_finalized INT NULL DEFAULT 0,
  remarks TEXT,
  created_by_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  updated_by_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  deleted_by_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE
);