CREATE TABLE IF NOT EXISTS inventories (
  id BIGSERIAL PRIMARY KEY,
  customer_id BIGINT REFERENCES customers(id) ON DELETE RESTRICT,
  io_type_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  currency_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  payment_term_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  warehouse_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  vat_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  pph23_id BIGINT REFERENCES mix_values(id) ON DELETE RESTRICT,
  branch_id BIGINT REFERENCES branches(id) ON DELETE RESTRICT,
  rev_no INT DEFAULT 0,
  inventory_no TEXT,
  inventory_no_ori TEXT,
  do_no TEXT,
  surat_jalan_no TEXT,
  invoice_no TEXT,
  ship_dest TEXT,
  remark TEXT,
  status TEXT DEFAULT 'DELIVERY',
  exchange_rate DECIMAL(20, 5),
  is_vat INT,
  vat_perc DECIMAL(20, 5),
  pph23_perc DECIMAL(20, 5),
  total_qty DECIMAL(20, 5),
  subtotal DECIMAL(20, 5),
  total_pph23 DECIMAL(20, 5),
  total_vat DECIMAL(20, 5),
  grand_total DECIMAL(20, 5),
  do_at date,
  ingoing_at date,
  invoice_at date,
  created_by_id BIGINT,
  updated_by_id BIGINT,
  deleted_by_id BIGINT,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone
)