{
 "title": "HTTP Request Count",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "route",
    "query": {
     "query": "label_values(http_requests_total, endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All req/s by res status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (response_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All req count by res status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1m])) by (response_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All req/s by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All req count by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{response_status=~\"4..\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Error Count (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{response_status=~\"4..\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{response_status=~\"5..\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Error Count (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{response_status=~\"5..\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/s By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{endpoint=~\"$route\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Requests By Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{endpoint=~\"$route\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}