name: s-erp-api

services:

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
      network: host
    ports:
      - "${GATEWAY_PORT:-80}:80"
    image: nibroos/s-erp-gateway-dev:1.0.250204
    networks:
      - s-erp-api-network
    depends_on:
      - service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      GATEWAY_PORT: ${GATEWAY_PORT}
      SERVICE_GRPC_PORT: ${SERVICE_GRPC_PORT}
      SERVICE_REST_PORT: ${SERVICE_REST_PORT}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      SERVICE_TYPE: main
    restart: on-failure

  service:
    build: 
      context: ../service
      dockerfile: Dockerfile.dev
      network: host
    image: nibroos/s-erp-service-dev:1.0.250216
    networks:
      - s-erp-api-network
    ports:
      - "${USERS_SERVICE_GRPC_PORT:-50051}:${USERS_SERVICE_GRPC_PORT:-50051}"
      - "4001:4001"
      - "4002:4001"
      - "4003:4001"
    depends_on:
      - postgres
    volumes:
      - ./../service:/apps
    env_file:
      - .env
    environment:
      SEEDER_DIR: /apps/internal/database/seeders
    restart: on-failure

  consumer-service:
    build: 
      context: ../service
      dockerfile: Dockerfile.dev
      network: host
    image: nibroos/s-erp-service-dev:1.0.250216
    networks:
      - s-erp-api-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: ${RABBITMQ_VHOST:-/}
      SERVICE_TYPE: consumer
    ports:
      - "4010:4010"
    volumes:
      - ./../service:/apps
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-s-erp-api
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      SERVICE_TYPE: consumer
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - s-erp-api-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-s_erp_api}
    networks:
      - s-erp-api-network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-s-erp-api:/var/lib/postgresql/data
    restart: on-failure

  # asynq-client:
  #   build:
  #     context: ../service
  #     dockerfile: Dockerfile.dev
  #     network: host
  #   image: nibroos/s-erp-asynq-client:1.0.250204
  #   networks:
  #     - s-erp-api-network
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     REDIS_DB: ${REDIS_DB}
  #   command: ["go", "run", "./client/main.go"]

  # asynq-server:
  #   build:
  #     context: ../service
  #     dockerfile: Dockerfile.dev
  #     network: host
  #   image: nibroos/s-erp-asynq-server:1.0.250204
  #   networks:
  #     - s-erp-api-network
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     REDIS_DB: ${REDIS_DB}
  #   command: ["go", "run", "./worker/server.go"]

  # redis:
  #   image: "redis:alpine"
  #   container_name: redis-s-erp-api
  #   networks:
  #     - s-erp-api-network
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
  #   command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  # scheduler:
  #   build:
  #     context: ../service
  #     dockerfile: Dockerfile.dev
  #   networks:
  #     - s-erp-api-network
  #   ports:
  #     - "4080:4080"
  #   depends_on:
  #     - postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     GATEWAY_PORT: ${GATEWAY_PORT}
  #     SERVICE_GRPC_PORT: ${SERVICE_GRPC_PORT}
  #     SERVICE_REST_PORT: ${SERVICE_REST_PORT}
  #     JWT_SECRET: ${JWT_SECRET}
  #     REDIS_HOST: ${REDIS_HOST}
  #     REDIS_PORT: ${REDIS_PORT}
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     REDIS_DB: ${REDIS_DB}
  #     SERVICE_TYPE: scheduler

  # asynq-ui:
  #   image: "hibiken/asynqmon:latest"
  #   container_name: asynq-ui-s-erp-api
  #   networks:
  #     - s-erp-api-network
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     REDIS_URL: "redis://redis:6379"
  #     REDIS_ADDR: "redis:6379"
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     REDIS_DB: ${REDIS_DB}

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - s-erp-api-network
    depends_on:
      - postgres
    restart: on-failure

  node-exporter:
    image: prom/node-exporter:v1.8.2
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - s-erp-api-network

  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - s-erp-api-network
    depends_on:
      - postgres-exporter
    restart: on-failure

  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - "3005:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - s-erp-api-network
    depends_on:
      - prometheus
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    networks:
      - s-erp-api-network
    environment:
      - discovery.type=single-node  # Run in single-node mode
      - xpack.ml.enabled=false  # Disable machine learning
      - xpack.security.enabled=false  # Disable security
      - xpack.monitoring.enabled=false  # Disable monitoring
      - xpack.watcher.enabled=false  # Disable watcher (alerting)
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10

  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - 16686:16686  # Jaeger UI
      - 14268:14268  # HTTP collector
      - 4317:4317  # OTLP gRPC
      - 4318:4318  # OTLP HTTP
    networks:
      - s-erp-api-network
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch  # Use Elasticsearch as the storage backend
      - ES_SERVER_URLS=http://elasticsearch:9200  # Elasticsearch server address
      - ES_TTL=168h  # Set TTL to 7 days (optional)
    depends_on:
      elasticsearch:
        condition: service_healthy

  # wkhtmltopdf:
  #   image: surnet/alpine-wkhtmltopdf:3.21.3-024b2b2-small
  #   container_name: wkhtmltopdf-s-erp-api
  #   networks:
  #     - s-erp-api-network
  #   ports:
  #     - "9000:9000"
  #   restart: on-failure

  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.77.0
  #   container_name: otel-collector-s-erp-api
  #   volumes:
  #     - ./otel-collector-config.yml:/etc/otel-collector-config.yml
  #   command: [ --config=/etc/otel-collector-config.yml ]
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.50"
  #         memory: 128M
  #       reservations:
  #         cpus: "0.20"
  #         memory: 20M
  #   ports:
  #     - 4317:4317  # OTLP gRPC
  #     - 4318:4318  # OTLP HTTP
  #     - 8889:8889 # Prometheus exporter metrics
  #   networks:
  #     - s-erp-api-network
  #   depends_on:
  #     - jaeger

volumes:
  postgres-s-erp-api:
  grafana-storage:
  # jaeger-logs:
  elasticsearch-data:
  rabbitmq-data:

networks:
  s-erp-api-network:
    driver: bridge
