BEGIN;

INSERT INTO
  company_profiles (
    parent_id,
    is_primary,
    company_owner_name,
    company_sign_name,
    company_name,
    company_address,
    company_phone,
    company_email,
    company_website,
    company_logo,
    company_description,
    company_remark,
    company_status,
    company_options_json,
    created_by_id,
    updated_by_id,
    deleted_by_id,
    created_at,
    updated_at
  )
VALUES
  (
    NULL,
    1,
    'Primary Company Owner',
    'Primary Company Owner Sign',
    'Primary Company',
    'Primary Company Address',
    'Primary Company Phone',
    'Primary Company Email',
    'Primary Company Website',
    'Primary Company Logo',
    'Primary Company Description',
    'Primary Company Remark',
    1,
    '{}',
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    1,
    0,
    'A Company Owner',
    'A Company Owner Sign',
    'A Company',
    'A Company Address',
    'A Company Phone',
    'A Company Email',
    'A Company Website',
    'A Company Logo',
    'A Company Description',
    'A Company Remark',
    1,
    '{}',
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    NULL,
    1,
    'C Company Owner',
    'C Company Owner Sign',
    'C Company',
    'C Company Address',
    'C Company Phone',
    'C Company Email',
    'C Company Website',
    'C Company Logo',
    'C Company Description',
    'C Company Remark',
    1,
    '{}',
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );

COMMIT;