BEGIN;

INSERT INTO
  branches (
    parent_id,
    company_profile_id,
    owner_name,
    sign_name,
    name,
    address,
    phone,
    email,
    website,
    logo,
    description,
    remark,
    status,
    options_json,
    created_by_id,
    updated_by_id,
    deleted_by_id,
    created_at,
    updated_at
  )
VALUES
  (
    NULL,
    1,
    'Primary Branch Owner',
    'Primary Branch Owner Sign',
    'Primary Branch',
    'Primary Branch Address',
    'Primary Branch Phone',
    'Primary Branch Email',
    'Primary Branch Website',
    'Primary Branch Logo',
    'Primary Branch Description',
    'Primary Branch Remark',
    1,
    '{}',
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    1,
    1,
    'Branch A Owner',
    'Branch A Owner Sign',
    'Branch A',
    'Branch A Address',
    'Branch A Phone',
    'Branch A Email',
    'Branch A Website',
    'Branch A Logo',
    'Branch A Description',
    'Branch A Remark',
    1,
    '{}',
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    1,
    1,
    'Branch B Owner',
    'Branch B Owner Sign',
    'Branch B',
    'Branch B Address',
    'Branch B Phone',
    'Branch B Email',
    'Branch B Website',
    'Branch B Logo',
    'Branch B Description',
    'Branch B Remark',
    1,
    '{}',
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    NULL,
    2,
    'Branch C Owner',
    'Branch C Owner Sign',
    'Branch C',
    'Branch C Address',
    'Branch C Phone',
    'Branch C Email',
    'Branch C Website',
    'Branch C Logo',
    'Branch C Description',
    'Branch C Remark',
    1,
    '{}',
    1,
    1,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );

COMMIT;